blank_issues_enabled: false
contact_links:
  - name: ğŸ Bug Report
    url: https://xenanetworks.com/support/bug-report/
    about: Create a report to help us improve XOA Python API.
  - name: âœ¨ Feature Request
    url: https://xenanetworks.com/support/feature-request/
    about: Suggest an idea for XOA Python API.
  - name: ğŸ§ Question
    url: https://xenanetworks.com/support/question/
    about: Ask us a question about XOA Python API.
  - name: ğŸ“ Check XOA Python API Documentation
    url: https://docs.xoa-python-api.xenanetworks.com
    about: The answer you are looking for may be in here.
  